version: '3.3'

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile  
    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example      
